name: executable
description: 'The executable package simplifies managing executables in Dart. Finds and checks presence, with cached results for improved performance.'
version: 1.4.0
repository: https://github.com/insign/dart_executable
homepage: https://github.com/insign/dart_executable

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  process_run: ^1.2.4

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3

platforms:
  linux:
  macos:
  windows:
