name: executable
description: Simple dart class to deal with executables
version: 1.0.0
repository: https://github.com/insign/dart_executable
homepage: https://github.com/insign/dart_executable

environment:
  sdk: '>=2.17.0 <3.0.0'
dependencies:
  process_run: ^0.12.5+2
dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

# Explicitly declare that this package works on all desktop platforms.
platforms:
  linux:
  macos:
  windows:
