// THIS FILE WAS GENERATED BY yaml2dart. EDIT IS NOT RECOMMENDED.
const name = 'executable';
const description =
    'The executable package simplifies managing executables in Dart. Finds and checks presence, with cached results for improved performance.';
const version = '1.4.0';
const repository = 'https://github.com/insign/dart_executable';
const homepage = 'https://github.com/insign/dart_executable';
const environment = '{sdk: >=2.17.0 <3.8.0}';
const dependencies = '{process_run: ^1.2.4}';
const devDependencies = '{lints: ^5.1.1, test: ^1.16.0}';
const platforms = '{linux: null, macos: null, windows: null}';
