// THIS FILE WAS GENERATED BY yaml2dart. EDIT IS NOT RECOMMENDED.
const name = 'executable';
const description =
    'The executable package simplifies managing executables in Dart. Finds and checks presence, with cached results for improved performance.';
const version = '1.2.3';
const repository = 'https://github.com/insign/dart_executable';
const homepage = 'https://github.com/insign/dart_executable';
const environment = '{sdk: >=2.17.0 <3.2.0}';
const dependencies = '{process_run: >=0.12.5+2 <0.14.0}';
const devDependencies = '{lints: ^3.0.0, test: ^1.16.0}';
const platforms = '{linux: null, macos: null, windows: null}';
