name: Publish to pub.dev

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"
  workflow_dispatch:

jobs:
  publish:
    permissions:
      id-token: write # This is required for authentication using OIDC
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
    # with:
    #   working-directory: path/to/package/within/repository
  notify:
    name: Notify the commit on Telegram
    runs-on: ubuntu-latest
    if: always()
    needs: publish
    steps:
      - uses: EverythingSuckz/github-telegram-notify@main
        with:
          bot_token: "${{ secrets.BOT_TOKEN }}"
          chat_id: "${{ secrets.CHAT_ID }}"
